# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-24 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='property',
            new_name='province',
        ),
    ]
